"""v0.05

Revision ID: 04ad260cac90
Revises: 356846734726
Create Date: 2026-08-20 15:26:10.266735

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "04ad260cac90"
down_revision: Union[str, Sequence[str], None] = "356846734726"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "M_MILESTONE",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("staff_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=256), nullable=True),
        sa.Column("color", sa.String(length=10), nullable=False),
        sa.Column("status", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("created_at", sa.Date(), nullable=False),
        sa.Column("guidline_end_date", sa.Date(), nullable=True),
        sa.Column("accomplished_date", sa.Date(), nullable=True),
        sa.ForeignKeyConstraint(
            ["staff_id"],
            ["M_LOGGININFO.STAFFID"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_M_MILESTONE_id"), "M_MILESTONE", ["id"], unique=False)
    op.create_index(op.f("ix_M_MILESTONE_title"), "M_MILESTONE", ["title"], unique=False)
    op.add_column("T_TIMELINE_EVENT", sa.Column("milestone_id", sa.Integer(), nullable=True))
    op.add_column(
        "T_TIMELINE_EVENT", sa.Column("completed", sa.Boolean(), server_default=sa.text("false"), nullable=False)
    )
    op.alter_column(
        "T_TIMELINE_EVENT",
        "progress",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.String(length=256),
        existing_nullable=True,
    )
    op.create_foreign_key(None, "T_TIMELINE_EVENT", "M_MILESTONE", ["milestone_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "T_TIMELINE_EVENT", type_="foreignkey")
    op.alter_column(
        "T_TIMELINE_EVENT",
        "progress",
        existing_type=sa.String(length=256),
        type_=sa.VARCHAR(length=255),
        existing_nullable=True,
    )
    op.drop_column("T_TIMELINE_EVENT", "completed")
    op.drop_column("T_TIMELINE_EVENT", "milestone_id")
    op.drop_index(op.f("ix_M_MILESTONE_title"), table_name="M_MILESTONE")
    op.drop_index(op.f("ix_M_MILESTONE_id"), table_name="M_MILESTONE")
    op.drop_table("M_MILESTONE")
    # ### end Alembic commands ###
