"""v0.04

Revision ID: 356846734726
Revises: 0f603c7ed865
Create Date: 2026-08-14 13:47:40.062627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '356846734726'
down_revision: Union[str, Sequence[str], None] = '0f603c7ed865'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('M_TEAM', 'SHORTNAME',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=25),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('M_TEAM', 'SHORTNAME',
               existing_type=sa.String(length=25),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###
