"""v0.01

Revision ID: c68df76a1ea5
Revises: 
Create Date: 2026-08-07 11:22:25.670365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c68df76a1ea5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('M_STAFFINFO',
    sa.Column('STAFFID', sa.Integer(), nullable=False),
    sa.Column('DEPARTMENT_CODE', sa.Integer(), nullable=True),
    sa.Column('TEAM_CODE', sa.Integer(), nullable=True),
    sa.Column('CONTRACT_CODE', sa.Integer(), nullable=True),
    sa.Column('JOBTYPE_CODE', sa.Integer(), nullable=True),
    sa.Column('POST_CODE', sa.Integer(), nullable=True),
    sa.Column('LNAME', sa.String(length=50), nullable=True),
    sa.Column('FNAME', sa.String(length=50), nullable=True),
    sa.Column('LKANA', sa.String(length=50), nullable=True),
    sa.Column('FKANA', sa.String(length=50), nullable=True),
    sa.Column('POST', sa.String(length=10), nullable=True),
    sa.Column('ADRESS1', sa.String(length=50), nullable=True),
    sa.Column('ADRESS2', sa.String(length=50), nullable=True),
    sa.Column('TEL1', sa.String(length=50), nullable=True),
    sa.Column('TEL2', sa.String(length=50), nullable=True),
    sa.Column('BIRTHDAY', sa.DateTime(), nullable=True),
    sa.Column('INDAY', sa.DateTime(), nullable=True),
    sa.Column('OUTDAY', sa.DateTime(), nullable=True),
    sa.Column('STANDDAY', sa.DateTime(), nullable=True),
    sa.Column('SOCIAL_INSURANCE', sa.Integer(), nullable=True),
    sa.Column('EMPLOYMENT_INSURANCE', sa.Integer(), nullable=True),
    sa.Column('EXPERIENCE', sa.Integer(), nullable=True),
    sa.Column('TABLET', sa.Integer(), nullable=True),
    sa.Column('SINGLE', sa.Integer(), nullable=True),
    sa.Column('SUPPORT', sa.Integer(), nullable=True),
    sa.Column('HOUSE', sa.Integer(), nullable=True),
    sa.Column('DISTANCE', sa.Float(), nullable=True),
    sa.Column('REMARK', sa.String(length=100), nullable=True),
    sa.Column('DISPLAY', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('STAFFID')
    )
    op.create_index(op.f('ix_M_STAFFINFO_ADRESS1'), 'M_STAFFINFO', ['ADRESS1'], unique=False)
    op.create_index(op.f('ix_M_STAFFINFO_ADRESS2'), 'M_STAFFINFO', ['ADRESS2'], unique=False)
    op.create_index(op.f('ix_M_STAFFINFO_BIRTHDAY'), 'M_STAFFINFO', ['BIRTHDAY'], unique=False)
    op.create_index(op.f('ix_M_STAFFINFO_CONTRACT_CODE'), 'M_STAFFINFO', ['CONTRACT_CODE'], unique=False)
    op.create_index(op.f('ix_M_STAFFINFO_DEPARTMENT_CODE'), 'M_STAFFINFO', ['DEPARTMENT_CODE'], unique=False)
    op.create_index(op.f('ix_M_STAFFINFO_DISPLAY'), 'M_STAFFINFO', ['DISPLAY'], unique=False)
    op.create_index(op.f('ix_M_STAFFINFO_DISTANCE'), 'M_STAFFINFO', ['DISTANCE'], unique=False)
    op.create_index(op.f('ix_M_STAFFINFO_EMPLOYMENT_INSURANCE'), 'M_STAFFINFO', ['EMPLOYMENT_INSURANCE'], unique=False)
    op.create_index(op.f('ix_M_STAFFINFO_EXPERIENCE'), 'M_STAFFINFO', ['EXPERIENCE'], unique=False)
    op.create_index(op.f('ix_M_STAFFINFO_FKANA'), 'M_STAFFINFO', ['FKANA'], unique=False)
    op.create_index(op.f('ix_M_STAFFINFO_FNAME'), 'M_STAFFINFO', ['FNAME'], unique=False)
    op.create_index(op.f('ix_M_STAFFINFO_HOUSE'), 'M_STAFFINFO', ['HOUSE'], unique=False)
    op.create_index(op.f('ix_M_STAFFINFO_INDAY'), 'M_STAFFINFO', ['INDAY'], unique=False)
    op.create_index(op.f('ix_M_STAFFINFO_JOBTYPE_CODE'), 'M_STAFFINFO', ['JOBTYPE_CODE'], unique=False)
    op.create_index(op.f('ix_M_STAFFINFO_LKANA'), 'M_STAFFINFO', ['LKANA'], unique=False)
    op.create_index(op.f('ix_M_STAFFINFO_LNAME'), 'M_STAFFINFO', ['LNAME'], unique=False)
    op.create_index(op.f('ix_M_STAFFINFO_OUTDAY'), 'M_STAFFINFO', ['OUTDAY'], unique=False)
    op.create_index(op.f('ix_M_STAFFINFO_POST'), 'M_STAFFINFO', ['POST'], unique=False)
    op.create_index(op.f('ix_M_STAFFINFO_POST_CODE'), 'M_STAFFINFO', ['POST_CODE'], unique=False)
    op.create_index(op.f('ix_M_STAFFINFO_REMARK'), 'M_STAFFINFO', ['REMARK'], unique=False)
    op.create_index(op.f('ix_M_STAFFINFO_SINGLE'), 'M_STAFFINFO', ['SINGLE'], unique=False)
    op.create_index(op.f('ix_M_STAFFINFO_SOCIAL_INSURANCE'), 'M_STAFFINFO', ['SOCIAL_INSURANCE'], unique=False)
    op.create_index(op.f('ix_M_STAFFINFO_STAFFID'), 'M_STAFFINFO', ['STAFFID'], unique=False)
    op.create_index(op.f('ix_M_STAFFINFO_STANDDAY'), 'M_STAFFINFO', ['STANDDAY'], unique=False)
    op.create_index(op.f('ix_M_STAFFINFO_SUPPORT'), 'M_STAFFINFO', ['SUPPORT'], unique=False)
    op.create_index(op.f('ix_M_STAFFINFO_TABLET'), 'M_STAFFINFO', ['TABLET'], unique=False)
    op.create_index(op.f('ix_M_STAFFINFO_TEAM_CODE'), 'M_STAFFINFO', ['TEAM_CODE'], unique=False)
    op.create_index(op.f('ix_M_STAFFINFO_TEL1'), 'M_STAFFINFO', ['TEL1'], unique=False)
    op.create_index(op.f('ix_M_STAFFINFO_TEL2'), 'M_STAFFINFO', ['TEL2'], unique=False)
    op.create_table('M_TEAM',
    sa.Column('CODE', sa.Integer(), nullable=False),
    sa.Column('NAME', sa.String(length=50), nullable=False),
    sa.Column('SHORTNAME', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('CODE')
    )
    op.create_index(op.f('ix_M_TEAM_CODE'), 'M_TEAM', ['CODE'], unique=False)
    op.create_index(op.f('ix_M_TEAM_NAME'), 'M_TEAM', ['NAME'], unique=False)
    op.create_index(op.f('ix_M_TEAM_SHORTNAME'), 'M_TEAM', ['SHORTNAME'], unique=False)
    op.create_table('M_LOGGININFO',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('STAFFID', sa.Integer(), nullable=False),
    sa.Column('PASSWORD_HASH', sa.String(length=128), nullable=True),
    sa.Column('ADMIN', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['STAFFID'], ['M_STAFFINFO.STAFFID'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_M_LOGGININFO_ADMIN'), 'M_LOGGININFO', ['ADMIN'], unique=False)
    op.create_index(op.f('ix_M_LOGGININFO_PASSWORD_HASH'), 'M_LOGGININFO', ['PASSWORD_HASH'], unique=False)
    op.create_index(op.f('ix_M_LOGGININFO_STAFFID'), 'M_LOGGININFO', ['STAFFID'], unique=True)
    op.create_table('T_TIMELINE_EVENT',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Date(), nullable=False),
    sa.Column('end_time', sa.Date(), nullable=False),
    sa.Column('title', sa.String(length=25), nullable=False),
    sa.Column('summary', sa.String(length=50), nullable=True),
    sa.Column('progress', sa.String(length=25), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['M_TEAM.CODE'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['M_LOGGININFO.STAFFID'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_T_TIMELINE_EVENT_id'), 'T_TIMELINE_EVENT', ['id'], unique=False)
    op.create_index(op.f('ix_T_TIMELINE_EVENT_progress'), 'T_TIMELINE_EVENT', ['progress'], unique=False)
    op.create_index(op.f('ix_T_TIMELINE_EVENT_title'), 'T_TIMELINE_EVENT', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_T_TIMELINE_EVENT_title'), table_name='T_TIMELINE_EVENT')
    op.drop_index(op.f('ix_T_TIMELINE_EVENT_progress'), table_name='T_TIMELINE_EVENT')
    op.drop_index(op.f('ix_T_TIMELINE_EVENT_id'), table_name='T_TIMELINE_EVENT')
    op.drop_table('T_TIMELINE_EVENT')
    op.drop_index(op.f('ix_M_LOGGININFO_STAFFID'), table_name='M_LOGGININFO')
    op.drop_index(op.f('ix_M_LOGGININFO_PASSWORD_HASH'), table_name='M_LOGGININFO')
    op.drop_index(op.f('ix_M_LOGGININFO_ADMIN'), table_name='M_LOGGININFO')
    op.drop_table('M_LOGGININFO')
    op.drop_index(op.f('ix_M_TEAM_SHORTNAME'), table_name='M_TEAM')
    op.drop_index(op.f('ix_M_TEAM_NAME'), table_name='M_TEAM')
    op.drop_index(op.f('ix_M_TEAM_CODE'), table_name='M_TEAM')
    op.drop_table('M_TEAM')
    op.drop_index(op.f('ix_M_STAFFINFO_TEL2'), table_name='M_STAFFINFO')
    op.drop_index(op.f('ix_M_STAFFINFO_TEL1'), table_name='M_STAFFINFO')
    op.drop_index(op.f('ix_M_STAFFINFO_TEAM_CODE'), table_name='M_STAFFINFO')
    op.drop_index(op.f('ix_M_STAFFINFO_TABLET'), table_name='M_STAFFINFO')
    op.drop_index(op.f('ix_M_STAFFINFO_SUPPORT'), table_name='M_STAFFINFO')
    op.drop_index(op.f('ix_M_STAFFINFO_STANDDAY'), table_name='M_STAFFINFO')
    op.drop_index(op.f('ix_M_STAFFINFO_STAFFID'), table_name='M_STAFFINFO')
    op.drop_index(op.f('ix_M_STAFFINFO_SOCIAL_INSURANCE'), table_name='M_STAFFINFO')
    op.drop_index(op.f('ix_M_STAFFINFO_SINGLE'), table_name='M_STAFFINFO')
    op.drop_index(op.f('ix_M_STAFFINFO_REMARK'), table_name='M_STAFFINFO')
    op.drop_index(op.f('ix_M_STAFFINFO_POST_CODE'), table_name='M_STAFFINFO')
    op.drop_index(op.f('ix_M_STAFFINFO_POST'), table_name='M_STAFFINFO')
    op.drop_index(op.f('ix_M_STAFFINFO_OUTDAY'), table_name='M_STAFFINFO')
    op.drop_index(op.f('ix_M_STAFFINFO_LNAME'), table_name='M_STAFFINFO')
    op.drop_index(op.f('ix_M_STAFFINFO_LKANA'), table_name='M_STAFFINFO')
    op.drop_index(op.f('ix_M_STAFFINFO_JOBTYPE_CODE'), table_name='M_STAFFINFO')
    op.drop_index(op.f('ix_M_STAFFINFO_INDAY'), table_name='M_STAFFINFO')
    op.drop_index(op.f('ix_M_STAFFINFO_HOUSE'), table_name='M_STAFFINFO')
    op.drop_index(op.f('ix_M_STAFFINFO_FNAME'), table_name='M_STAFFINFO')
    op.drop_index(op.f('ix_M_STAFFINFO_FKANA'), table_name='M_STAFFINFO')
    op.drop_index(op.f('ix_M_STAFFINFO_EXPERIENCE'), table_name='M_STAFFINFO')
    op.drop_index(op.f('ix_M_STAFFINFO_EMPLOYMENT_INSURANCE'), table_name='M_STAFFINFO')
    op.drop_index(op.f('ix_M_STAFFINFO_DISTANCE'), table_name='M_STAFFINFO')
    op.drop_index(op.f('ix_M_STAFFINFO_DISPLAY'), table_name='M_STAFFINFO')
    op.drop_index(op.f('ix_M_STAFFINFO_DEPARTMENT_CODE'), table_name='M_STAFFINFO')
    op.drop_index(op.f('ix_M_STAFFINFO_CONTRACT_CODE'), table_name='M_STAFFINFO')
    op.drop_index(op.f('ix_M_STAFFINFO_BIRTHDAY'), table_name='M_STAFFINFO')
    op.drop_index(op.f('ix_M_STAFFINFO_ADRESS2'), table_name='M_STAFFINFO')
    op.drop_index(op.f('ix_M_STAFFINFO_ADRESS1'), table_name='M_STAFFINFO')
    op.drop_table('M_STAFFINFO')
    # ### end Alembic commands ###
