"""v0.08

Revision ID: e07d32194539
Revises: e0fbbca5c733
Create Date: 2026-10-02 16:30:14.428839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e07d32194539'
down_revision: Union[str, Sequence[str], None] = 'e0fbbca5c733'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('T_TIMELINE_EVENT', 'summary',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=256),
               existing_nullable=True)
    op.alter_column('T_TIMELINE_EVENT', 'progress',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=10),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('T_TIMELINE_EVENT', 'progress',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=256),
               existing_nullable=True)
    op.alter_column('T_TIMELINE_EVENT', 'summary',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###
